# Generated by Django 4.0.5 on 2022-09-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
