# Generated by Django 4.0.5 on 2022-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
                ('password', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
