# Generated by Django 4.0.5 on 2022-09-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbankregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('bgroup', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
