# Generated by Django 3.2.5 on 2023-01-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20230112_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='counter',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
