# Generated by Django 4.0.5 on 2022-10-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_connect_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='Lastdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='connect',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
