# Generated by Django 4.0.5 on 2022-09-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Task', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=60)),
                ('Duedate', models.DateField()),
            ],
        ),
    ]
