# Generated by Django 4.0.5 on 2022-09-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Duedate',
            new_name='duedate',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Task',
            new_name='task',
        ),
    ]
